# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontend_settings.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66rontend_settings.proto\x12\x11\x66rontend_settings\"Z\n\x13PreferenceInstances\x12\x43\n\x14preference_instances\x18\x01 \x03(\x0b\x32%.frontend_settings.PreferenceInstance\"\xd5\x01\n\x17RequestObjectForPalette\x12Z\n\x11tmo_id_preference\x18\x01 \x03(\x0b\x32?.frontend_settings.RequestObjectForPalette.TmoIdPreferenceEntry\x1a^\n\x14TmoIdPreferenceEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32&.frontend_settings.PreferenceInstances:\x02\x38\x01\"O\n\x12PreferenceInstance\x12\x17\n\x0fpreference_name\x18\x01 \x01(\t\x12\x10\n\x08val_type\x18\x02 \x01(\t\x12\x0e\n\x06kpi_id\x18\x03 \x01(\x05\"$\n\x0bWrongKpiIds\x12\x15\n\rwrong_kpi_ids\x18\x01 \x03(\x05\"\x86\x01\n PreferenceInstanceForWithPalette\x12\x17\n\x0fpreference_name\x18\x01 \x01(\t\x12\x10\n\x08val_type\x18\x02 \x01(\t\x12\x0e\n\x06kpi_id\x18\x03 \x01(\x05\x12\x0f\n\x07palette\x18\x04 \x01(\t\x12\x16\n\x0eobject_type_id\x18\x05 \x01(\x05\"n\n\x19RequestToSetCustomPalette\x12Q\n\x14preference_instances\x18\x01 \x03(\x0b\x32\x33.frontend_settings.PreferenceInstanceForWithPalette2\xea\x01\n\x10\x46rontendSettings\x12i\n\x19SetDefaultPaletteForItems\x12*.frontend_settings.RequestObjectForPalette\x1a\x1e.frontend_settings.WrongKpiIds\"\x00\x12k\n\x19SetCustomColorRangeForKPI\x12,.frontend_settings.RequestToSetCustomPalette\x1a\x1e.frontend_settings.WrongKpiIds\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frontend_settings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTOBJECTFORPALETTE_TMOIDPREFERENCEENTRY']._options = None
  _globals['_REQUESTOBJECTFORPALETTE_TMOIDPREFERENCEENTRY']._serialized_options = b'8\001'
  _globals['_PREFERENCEINSTANCES']._serialized_start=46
  _globals['_PREFERENCEINSTANCES']._serialized_end=136
  _globals['_REQUESTOBJECTFORPALETTE']._serialized_start=139
  _globals['_REQUESTOBJECTFORPALETTE']._serialized_end=352
  _globals['_REQUESTOBJECTFORPALETTE_TMOIDPREFERENCEENTRY']._serialized_start=258
  _globals['_REQUESTOBJECTFORPALETTE_TMOIDPREFERENCEENTRY']._serialized_end=352
  _globals['_PREFERENCEINSTANCE']._serialized_start=354
  _globals['_PREFERENCEINSTANCE']._serialized_end=433
  _globals['_WRONGKPIIDS']._serialized_start=435
  _globals['_WRONGKPIIDS']._serialized_end=471
  _globals['_PREFERENCEINSTANCEFORWITHPALETTE']._serialized_start=474
  _globals['_PREFERENCEINSTANCEFORWITHPALETTE']._serialized_end=608
  _globals['_REQUESTTOSETCUSTOMPALETTE']._serialized_start=610
  _globals['_REQUESTTOSETCUSTOMPALETTE']._serialized_end=720
  _globals['_FRONTENDSETTINGS']._serialized_start=723
  _globals['_FRONTENDSETTINGS']._serialized_end=957
# @@protoc_insertion_point(module_scope)
