"""Add permission table

Revision ID: 40e4192e8546
Revises: 50f2dad864b6
Create Date: 2024-06-03 16:47:04.667681+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e4192e8546'
down_revision = '50f2dad864b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_permission',
    sa.Column('root_permission_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.Column('create', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('update', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['kpi.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_permission_id'], ['kpi_permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'permission')
    )
    op.create_index(op.f('ix_kpi_permission_parent_id'), 'kpi_permission', ['parent_id'], unique=False)
    op.create_index(op.f('ix_kpi_permission_root_permission_id'), 'kpi_permission', ['root_permission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_permission_root_permission_id'), table_name='kpi_permission')
    op.drop_index(op.f('ix_kpi_permission_parent_id'), table_name='kpi_permission')
    op.drop_table('kpi_permission')
    # ### end Alembic commands ###
