"""add indexes for kpi values

Revision ID: c875424dbf9b
Revises: 8b531ffe87b5
Create Date: 2024-05-07 11:59:53.938464+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c875424dbf9b'
down_revision = '8b531ffe87b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_kpi_values_granularity_id'), 'kpi_values', ['granularity_id'], unique=False)
    op.create_index(op.f('ix_kpi_values_kpi_id'), 'kpi_values', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_kpi_values_object_id'), 'kpi_values', ['object_id'], unique=False)
    op.create_index(op.f('ix_kpi_values_record_time'), 'kpi_values', ['record_time'], unique=False)
    op.create_index(op.f('ix_kpi_values_state'), 'kpi_values', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_values_state'), table_name='kpi_values')
    op.drop_index(op.f('ix_kpi_values_record_time'), table_name='kpi_values')
    op.drop_index(op.f('ix_kpi_values_object_id'), table_name='kpi_values')
    op.drop_index(op.f('ix_kpi_values_kpi_id'), table_name='kpi_values')
    op.drop_index(op.f('ix_kpi_values_granularity_id'), table_name='kpi_values')
    # ### end Alembic commands ###
