"""Added label for KPI

Revision ID: ae770d64f644
Revises: c875424dbf9b
Create Date: 2024-05-10 16:46:11.727711+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae770d64f644'
down_revision = 'c875424dbf9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'label')
    # ### end Alembic commands ###
