"""Add related kpi

Revision ID: e68cc32aae26
Revises: 40e4192e8546
Create Date: 2024-06-13 14:03:32.990527+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68cc32aae26'
down_revision = '40e4192e8546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_kpis',
    sa.Column('main_kpi', sa.Integer(), nullable=False),
    sa.Column('related_kpi', sa.Integer(), nullable=False),
    sa.CheckConstraint('main_kpi != related_kpi', name='check_main_related_kpi_not_equal'),
    sa.ForeignKeyConstraint(['main_kpi'], ['kpi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_kpi'], ['kpi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('main_kpi', 'related_kpi')
    )
    op.create_index(op.f('ix_related_kpis_main_kpi'), 'related_kpis', ['main_kpi'], unique=False)
    op.create_index(op.f('ix_related_kpis_related_kpi'), 'related_kpis', ['related_kpi'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_related_kpis_related_kpi'), table_name='related_kpis')
    op.drop_index(op.f('ix_related_kpis_main_kpi'), table_name='related_kpis')
    op.drop_table('related_kpis')
    # ### end Alembic commands ###
