"""Add group for kpi

Revision ID: 450bf0c20bff
Revises: e68cc32aae26
Create Date: 2024-07-15 17:03:40.278353+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450bf0c20bff'
down_revision = 'e68cc32aae26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'group')
    # ### end Alembic commands ###
