"""parent-child links

Revision ID: 328d614e7265
Revises: 450bf0c20bff
Create Date: 2024-08-25 11:33:09.413667+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328d614e7265'
down_revision = '450bf0c20bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('parent_kpi', sa.Integer(), nullable=True))
    op.add_column('kpi', sa.Column('child_kpi', sa.Integer(), nullable=True))
    op.create_foreign_key('kpi_child_kpi_fkey', 'kpi', 'kpi', ['child_kpi'], ['id'])
    op.create_foreign_key('kpi_parent_kpi_fkey', 'kpi', 'kpi', ['parent_kpi'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('kpi_parent_kpi_fkey', 'kpi', type_='foreignkey')
    op.drop_constraint('kpi_child_kpi_fkey', 'kpi', type_='foreignkey')
    op.drop_column('kpi', 'child_kpi')
    op.drop_column('kpi', 'parent_kpi')
    # ### end Alembic commands ###
