"""Add field brach

Revision ID: 3ed206a37e48
Revises: 328d614e7265
Create Date: 2024-08-27 13:58:54.415839+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed206a37e48'
down_revision = '328d614e7265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'branch')
    # ### end Alembic commands ###
