# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airflow_to_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61irflow_to_state.proto\x12\x0cobject_state\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n\x03KPI\x12\x0e\n\x06kpi_id\x18\x01 \x01(\x03\x12\x11\n\tobject_id\x18\x02 \x01(\x03\x12\x16\n\x0egranularity_id\x18\x03 \x01(\x03\x12\r\n\x05value\x18\x04 \x01(\t\x12/\n\x0brecord_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12#\n\x05state\x18\x06 \x01(\x0e\x32\x14.object_state.States\"9\n\x12RequestBatchImport\x12#\n\x08kpi_data\x18\x01 \x03(\x0b\x32\x11.object_state.KPI\"G\n\x13ResponseBatchImport\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message*2\n\x06States\x12\x0b\n\x07\x63urrent\x10\x00\x12\x0e\n\nhistorical\x10\x01\x12\x0b\n\x07planned\x10\x02\x32o\n\x15\x41irflowToStateManager\x12V\n\x0b\x42\x61tchImport\x12 .object_state.RequestBatchImport\x1a!.object_state.ResponseBatchImport\"\x00(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'airflow_to_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATES._serialized_start=373
  _STATES._serialized_end=423
  _KPI._serialized_start=74
  _KPI._serialized_end=239
  _REQUESTBATCHIMPORT._serialized_start=241
  _REQUESTBATCHIMPORT._serialized_end=298
  _RESPONSEBATCHIMPORT._serialized_start=300
  _RESPONSEBATCHIMPORT._serialized_end=371
  _AIRFLOWTOSTATEMANAGER._serialized_start=425
  _AIRFLOWTOSTATEMANAGER._serialized_end=536
# @@protoc_insertion_point(module_scope)
