# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import airflow_to_state_pb2 as airflow__to__state__pb2


class AirflowToStateManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchImport = channel.stream_unary(
                '/object_state.AirflowToStateManager/BatchImport',
                request_serializer=airflow__to__state__pb2.RequestBatchImport.SerializeToString,
                response_deserializer=airflow__to__state__pb2.ResponseBatchImport.FromString,
                )


class AirflowToStateManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BatchImport(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AirflowToStateManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchImport': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchImport,
                    request_deserializer=airflow__to__state__pb2.RequestBatchImport.FromString,
                    response_serializer=airflow__to__state__pb2.ResponseBatchImport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'object_state.AirflowToStateManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AirflowToStateManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BatchImport(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/object_state.AirflowToStateManager/BatchImport',
            airflow__to__state__pb2.RequestBatchImport.SerializeToString,
            airflow__to__state__pb2.ResponseBatchImport.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
